### ISSUE TITLE
How do you adjust the height of the tabs?

### ISSUE THREAD

**Issue by VicFrolov** [pepjo/react-tabs-navigation#6]
I tried setting a class with a height to the Tabs component, but that didn't work. when I go into dev tools with chrome it seems that "nav" is what is being set, but changing that would affect my actual navbar.

**Comment by pepjo** [comment]
Hi!

you should be able to provide an object to the prop `tabsBarStyle` with a different `height`.

You can see here the default value: https://github.com/pepjo/react-tabs-navigation/blob/master/src/tabs.js#L25
